### ISSUE TITLE
http://localhost:80/ocsreports is broken

### ISSUE THREAD

**Issue by jgoerzen** [OCSInventory-NG/OCSInventory-Docker-Image#1]
http://wiki.ocsinventory-ng.org/index.php?title=Documentation:Server says that /ocsreports should be accessible.  But it's not.

In `/etc/apache2/conf-enabled/ocsinventory-reports.conf`, there is this line:

`Alias /ocsreports /usr/share/ocsinventory-reports/ocsreports`

However:

# ls -l /usr/share/ocsinventory-reports/ocsreports
ls: cannot access /usr/share/ocsinventory-reports/ocsreports: No such file or directory
# ls -l /usr/share/ocsinventory-reports 
total 3
drwxr-xr-x 2 www-data www-data 2 Mar 18 13:58 download
drwxr-xr-x 2 www-data www-data 2 Mar 18 13:58 ipd
drwxr-xr-x 2 www-data www-data 2 Mar 18 13:58 logs
drwxr-xr-x 2 www-data www-data 2 Mar 18 13:58 scripts
drwxr-xr-x 2 www-data www-data 2 Mar 18 13:58 snmp

It seems that ocsreports is missing.  According to the docs, this is how to set up the system and log in, so it is unclear how to proceed from here.

**Comment by gillesdubois** [comment]
Hi @jgoerzen ,

SInce you are using the docker image, have you checked the read me before trying to run it ?
https://github.com/OCSInventory-NG/OCSInventory-Docker-Image/blob/master/README.md

Regards,
Gilles Dubois.

**Comment by jgoerzen** [comment]
Hi,

This was actually started by docker-compose as a member of https://github.com/OCSInventory-NG/OCSInventory-Docker-Stack .  I did read both READMEs, but neither mentioned anything that seems relevant to this.  If you think I missed something, please let me know.

**Comment by zerossB** [comment]
I'm having the same problem, but when I run the OCSInventory container for the first time, it appears normally and runs normal, if I stop the container and run it again it loses the reference and returns me a 404.

Now all other routes (/ocsinventory, /download and /snmp) work normally, only /ocsreports does not work :/

**Comment by zerossB** [comment]
@jgoerzen The problem is this part here:

https://github.com/OCSInventory-NG/OCSInventory-Docker-Stack/blob/master/docker-compose.yml#L15

For the time he creates the container, it overrides the things in the volume "ocssrv", so that there is no folder (ocsreports) within the volume, because the content is overwritten by the contents of the folder (/var/lib/ocsinventory-reports/).

However, the download, snmp, and ocsinventory folders are no longer available for use.
I created a new volume for these folders and everything returned to normal ;D

**Comment by MyTheValentinus** [comment]
Hello,
Yes that normal, I think I will delete ocssrv from docker-composer.yml, it's misleading
Thanks
