### ISSUE TITLE
Option to overwrite mysql-port

### ISSUE THREAD

**Issue by julian-eggers** [OCSInventory-NG/OCSInventory-Docker-Image#16]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : Ubuntu 18.04
Mysql Server version : MariaDB 10.0

### Docker informations
Docker compose version : -
Docker version : 18.09

### Problem's description
My mariadb/mysql-server is running on a port different to 3306.
I need an option to overwrite the default-port.
This has to be done in "z-ocsinventory-server.conf, where all other server-properties are set.

**Comment by gillesdubois** [comment]
Hi,

Our Docker image has been reworked completly.
2.6 / nightly / dev tags are now available.

A complete documentation is available on our wiki.
Compose files are now located on the image repository and not on this one anymore.

Extension engine has been rework since it suffered from a bug in the earliers versions.

Regards,
Gilles Dubois.
